name: "docker-build-push"
description: "build and push docker image"
inputs: 
  IMAGES:
     required: true
  DEPLOY_URL: 
    required: true
  USE_PULL_REPO:
    required: false
    default: "true"
runs:
  using: "composite"
  steps:

    - name: change to pull repos
      shell: bash
      run:  |
        echo "PULL_IMAGES=$(echo '${{ steps.docker_build.outputs.images }}' | sed 's/([^.]*)/\1-pull/')" >> $GITHUB_ENV
      if: ${{ inputs.USE_PULL_REPO == 'true' }}

    - name: change to pull repos
      shell: bash
      run:  echo "PULL_IMAGES=${{ steps.docker_build.outputs.images }}" >> $GITHUB_ENV
      if: ${{ inputs.USE_PULL_REPO == 'false' }}

    - name: deploy
      shell: bash
      run:  |
        curl -H 'X-Authorization: ${{ secrets.AUTH_TOKEN }}' -H 'X-Deploy-Tags: ${{ env.PULL_IMAGES }}' ${{ inputs.DEPLOY_URL }} 

