name: "docker-build-push"
description: "build and push docker image"
inputs: 
  IMAGES:
     required: true
  DEPLOY_URL: 
    required: true
  USE_PULL_REPO:
    required: false
    default: "true"
runs:
  using: "composite"
  steps:

    - name: deploy
      shell: bash
      run:  |
        curl -H 'X-Authorization: ${{ secrets.AUTH_TOKEN }}' -H 'X-Deploy-Tags: ${{ inputs.IMAGES }}' ${{ inputs.DEPLOY_URL }} 

