name: build and deploy

on:
  workflow_call:
    inputs:
      DOCKER_REPO:
         required: true
         type: string
      DOCKER_REGISTRY: 
        required: true
        type: string
      DOCKER_USER:
        required: false
        default: "builder"
        type: string
      QEMU_SETUP:
        required: false
        default: "false"
        type: string
      DEPLOY_URL: 
        required: false
        default: "INVALID"        
        type: string
      USE_PULL_REPO:
        required: false
        type: string        
        default: "true"        
    secrets:
      DOCKER_PASSWORD:
        required: true
      AUTH_TOKEN:
        required: false

jobs:
  docker_build:
    name: "build docker image and deploy"
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: [self-hosted]
    
    steps:

      - uses: actions/checkout@v2

      - name: build
        shell: bash
        run:  |
          mkdir build

      - uses: athenarc/actions-docker-build-push@master
        id: docker_build
        with:
          DOCKER_REGISTRY: "${{ inputs.DOCKER_REGISTRY }}"
          DOCKER_REPO: "${{ inputs.DOCKER_REPO }}"
          QEMU_SETUP: "${{ inputs.QEMU_SETUP }}"
          DOCKER_USER: "${{ inputs.DOCKER_USER }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - name: change to pull repos
        shell: bash
        id: set_pull_repos
        run:  |
          echo "::set-output name=images::$(echo '${{ steps.docker_build.outputs.images }}' | sed 's/^\([^.]*\)/\1-pull/')"
        if: ${{ inputs.USE_PULL_REPO == 'true' }}

      - name: deploy
        shell: bash
        run:  |
          curl -H 'X-Authorization: ${{ secrets.AUTH_TOKEN }}' -H "X-Deploy-Tags: ${{ steps.set_pull_repos.outputs.images }}" ${{ inputs.DEPLOY_URL }} 
        if: ${{ inputs.DEPLOY_URL != 'INVALID' && inputs.USE_PULL_REPO == 'true' }}

      - name: deploy
        shell: bash
        run:  |
          curl -H 'X-Authorization: ${{ secrets.AUTH_TOKEN }}' -H 'X-Deploy-Tags: ${{ steps.docker_build.outputs.images }}' ${{ inputs.DEPLOY_URL }} 
        if: ${{ inputs.DEPLOY_URL != 'INVALID' && inputs.USE_PULL_REPO == 'false' }}

      # - uses: athenarc/actions-docker-compose-deploy@master
      #   id: docker_deploy
      #   with:
      #     AUTH_TOKEN: "${{ secrets.AUTH_TOKEN }}"
      #     USE_PULL_REPO: "${{ inputs.USE_PULL_REPO }}"
      #     DEPLOY_URL: "${{ inputs.DEPLOY_URL }}"
